version: "3.9"
services:
  fastapi:
    image: test/fastapi
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload
    build:
      context: ./app
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
    environment:
      SQL_DB_HOST: ${SQL_DB_HOST}
      SQL_DB_PORT: ${SQL_DB_PORT}
      SQL_DB_NAME: ${SQL_DB_NAME}
      SQL_DB_USER: ${SQL_DB_USER}
      SQL_DB_PASSWORD: ${SQL_DB_PASSWORD}

      NOSQL_DB_HOST: ${NOSQL_DB_HOST}
      NOSQL_DB_PORT: ${NOSQL_DB_PORT}
      NOSQL_DB_NAME: ${NOSQL_DB_NAME}
      NOSQL_DB_USER: ${NOSQL_DB_USER}
      NOSQL_DB_PASSWORD: ${NOSQL_DB_PASSWORD}
