version: '3'
services:
  fastapi:
    image: test/fastapi
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload
    build:
      context: ./app
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"