version: "3.9"
services:
  fastapi:
    image: test/fastapi
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload
    build:
      context: ./app
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}