commonLabels:
- { kind: DeploymentConfig, path: spec/template/metadata/labels, create: true }
- { kind: DeploymentConfig, path: spec/selector, create: true }

varReference:
  - { kind: HorizontalPodAutoscaler, path: spec/scaleTargetRef/name } 

nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - { kind: DeploymenConfig, path: spec/template/spec/volumes/secret/secretName }
  - { kind: DeploymenConfig, path: spec/template/secret/secretName }