FROM python:3.9-slim-buster

WORKDIR /app

COPY ./requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./src /app

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]