apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: price-poc-prod

commonLabels:
  app: price-poc
  env: prod

patchesStrategicMerge:
  - patch-resources.yaml
  - patch-db-env.yaml