apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: price-poc
  name: price-poc
spec:
  rules:
    - host: ''
      http:
        paths:
          - path: /prod/?(.*)
            pathType: Prefix
            backend:
              service:
                name: price-poc  # Replace it with the name of your target Service.
                port:
                  number: 8080  # Replace 8080 with the port number of your target Service.
            property:
              ingress.beta.kubernetes.io/url-match-mode: STARTS_WITH
  ingressClassName: nginx    # Nginx ingress is used.
