apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-poc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: price-poc
          image: 'swr.ap-southeast-2.myhuaweicloud.com/price-poc/fastapi:latest'
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: price-db-dev-69bctbb4h7
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: price-db-dev-69bctbb4h7
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: price-db-dev-69bctbb4h7
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: price-db-dev-69bctbb4h7
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: price-db-dev-69bctbb4h7
                  key: DB_PASSWORD
      imagePullSecrets:
      - name: default-secret