apiVersion: v1
kind: Service
metadata:
  labels:
    app: price-poc
  name: price-poc
# spec: 
#   ports: 
#   - name: price-poc
#     port: 8080
#     protocol: TCP 
#     targetPort: 8080
#   selector: 
#     app: price-poc 
#   type: LoadBalancer