apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.id: 4f1ee94d-fc03-4d69-9abf-13d6a5eaf12d # Load balancer ID. Replace it with the actual value.
  labels:
    app: price-poc
  name: price-poc
spec: 
  ports: 
  - name: price-poc 
    port: 8080
    protocol: TCP 
    targetPort: 8080
  selector: 
    app: price-poc 
  type: LoadBalancer