apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.id: 4f1ee94d-fc03-4d69-9abf-13d6a5eaf12d
  labels:
    app: price-poc
    env: dev
  name: price-poc
  namespace: price-poc-dev
spec:
  ports:
  - name: price-poc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: price-poc
    env: dev
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: price-poc
    env: dev
  name: price-poc
  namespace: price-poc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-poc
      env: dev
  template:
    metadata:
      labels:
        app: price-poc
        env: dev
    spec:
      containers:
      - image: swr.ap-southeast-2.myhuaweicloud.com/price-poc/fastapi:latest
        imagePullPolicy: Always
        name: price-poc
        resources:
          limits:
            cpu: 400m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 512Mi
      imagePullSecrets:
      - name: default-secret
