apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: price-poc-dev

# setting env for config
# secretGenerator:
# - name: price-db-dev
#   envs:
#   - dev.env

commonLabels:
  app: price-poc
  env: dev

patchesStrategicMerge:
  - patch-resources.yaml
  - patch-db-env.yaml