apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: price-poc-dev

secretGenerator:
- name: price-db-dev
  envs:
  - .env.secret

commonLabels:
  app: price-poc
  env: dev

patchesStrategicMerge:
  - patch-resources.yaml