apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: price-poc-dev

commonLabels:
  app: price-poc
  env: dev

patchesStrategicMerge:
  - patch-resources.yaml
  - patch-db-env.yaml
  - patch-ingress.yaml
  - patch-service.yaml